# Job Market Intelligence & Skills Analytics

## 01 — API Data Collection

This notebook connects to the Adzuna API, retrieves job-market data in JSON format, and performs the initial validation of the API response.

In [1]:
import os
import requests
from dotenv import load_dotenv

load_dotenv()

APP_ID = os.getenv("ADZUNA_APP_ID")
APP_KEY = os.getenv("ADZUNA_APP_KEY")

print("App ID loaded:", APP_ID is not None)
print("App Key loaded:", APP_KEY is not None)

App ID loaded: True
App Key loaded: True

In [2]:
url = "https://api.adzuna.com/v1/api/jobs/gb/search/1"

params = {
    "app_id": APP_ID,
    "app_key": APP_KEY,
    "what": "data analyst",
    "where": "London",
    "results_per_page": 10,
    "content-type": "application/json"
}

response = requests.get(url, params=params, timeout=30)

print("Status code:", response.status_code)

Status code: 200

## 2. Inspect the API Response

The API request returned a successful response. We will now inspect the JSON structure to understand the available fields before transforming the data.

In [3]:
data = response.json()

print("Response type:", type(data))
print("Top-level keys:", list(data.keys()))

Response type: <class 'dict'>
Top-level keys: ['results', 'mean', '__CLASS__', 'count']

In [4]:
print("Total jobs reported by API:", data.get("count"))
print("Jobs returned in this request:", len(data.get("results", [])))

Total jobs reported by API: 837
Jobs returned in this request: 10

In [5]:
from pprint import pprint

pprint(data["results"][0])

{'__CLASS__': 'Adzuna::API::Response::Job',
 'adref': 'eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgzODM4MTQ1OCIsInMiOiJrQVBCeVhXdjhSR0lxNWo1dTR4TEp3In0.0xyQqZpNlyCY-kPCuacuVj9EiRBovhN1B0UT80tAUWg',
 'category': {'__CLASS__': 'Adzuna::API::Response::Category',
              'label': 'Accounting & Finance Jobs',
              'tag': 'accounting-finance-jobs'},
 'company': {'__CLASS__': 'Adzuna::API::Response::Company',
             'display_name': 'Wise'},
 'contract_time': 'full_time',
 'contract_type': 'contract',
 'created': '2026-08-12T15:38:55Z',
 'description': 'Wise is a global technology company, building the best way to '
                'move and manage the world’s money. Min fees. Max ease. Full '
                'speed. Whether people and businesses are sending money to '
                'another country, spending abroad, or making and receiving '
                'international payments, Wise is on a mission to make their '
                'lives easier and save them money. As part of our team, you '
                'will be helping us create an entirely new network for the '
                'worlds money. For everyone, everywhere. Job Description We '
                'are looking for a Lead Dat…',
 'id': '5838381458',
 'latitude': 51.503378,
 'location': {'__CLASS__': 'Adzuna::API::Response::Location',
              'area': ['UK', 'London'],
              'display_name': 'London, UK'},
 'longitude': -0.139134,
 'redirect_url': 'https://www.adzuna.co.uk/jobs/land/ad/5838381458?se=kAPByXWv8RGIq5j5u4xLJw&utm_medium=api&utm_source=5ec7ac9c&v=16724A4F9650B061C6F788C6F84950F31715427D',
 'salary_is_predicted': '1',
 'salary_max': 71829.23,
 'salary_min': 71829.23,
 'title': 'Lead Data Analyst'}

## 3. Save Raw API Response

The original JSON response is saved before any transformation or cleaning. This preserves the source data and allows the extraction process to be reproduced.

In [6]:
import json

raw_file_path = "../data/raw/adzuna_data_uk_data_analyst_london.json"

with open(raw_file_path, "w", encoding="utf-8") as file:
    json.dump(data, file, indent=2, ensure_ascii=False)

print(f"Raw API response saved to: {raw_file_path}")

Raw API response saved to: ../data/raw/adzuna_data_uk_data_analyst_london.json

## 4. Convert Job Listings to a DataFrame

The `results` section contains individual job listings. We will extract these records into a Pandas DataFrame for structured analysis.

In [7]:
import pandas as pd

jobs = data["results"]

df = pd.json_normalize(jobs)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 10
Columns: 22

In [8]:
df.head()

,created,__CLASS__,contract_time,longitude,salary_min,description,title,latitude,redirect_url,salary_is_predicted,...,adref,contract_type,category.tag,category.label,category.__CLASS__,location.__CLASS__,location.display_name,location.area,company.display_name,company.__CLASS__
0,2026-08-12T15:38:55Z,Adzuna::API::Response::Job,full_time,-0.139134,71829.23,"Wise is a global technology company, building ...",Lead Data Analyst,51.503378,https://www.adzuna.co.uk/jobs/land/ad/58383814...,1,...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgzODM4MTQ1OCIsI...,contract,accounting-finance-jobs,Accounting & Finance Jobs,Adzuna::API::Response::Category,Adzuna::API::Response::Location,"London, UK","[UK, London]",Wise,Adzuna::API::Response::Company
1,2026-09-11T13:56:37Z,Adzuna::API::Response::Job,full_time,-0.139134,49156.57,"£45,000 - 60,000 GBP Pension, Benefits Hybrid ...",Data Analyst,51.503378,https://www.adzuna.co.uk/jobs/land/ad/58797497...,1,...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoia0FQQnlYV3Y4UkdJc...,permanent,it-jobs,IT Jobs,Adzuna::API::Response::Category,Adzuna::API::Response::Location,"London, UK","[UK, London]",Anson Mccade,Adzuna::API::Response::Company
2,2026-08-29T15:29:41Z,Adzuna::API::Response::Job,full_time,-0.139134,46263.40,The Risk Technology Data Analyst will be a key...,Risk Technology Data Analyst,51.503378,https://www.adzuna.co.uk/jobs/land/ad/58611823...,1,...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoia0FQQnlYV3Y4UkdJc...,NaN,it-jobs,IT Jobs,Adzuna::API::Response::Category,Adzuna::API::Response::Location,"London, UK","[UK, London]",BGC Partners,Adzuna::API::Response::Company
3,2026-08-12T15:39:11Z,Adzuna::API::Response::Job,full_time,-0.139134,88466.81,"Wise is a global technology company, building ...","Staff Data Analyst, Operations",51.503378,https://www.adzuna.co.uk/jobs/land/ad/58383834...,1,...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgzODM4MzQzOSIsI...,contract,it-jobs,IT Jobs,Adzuna::API::Response::Category,Adzuna::API::Response::Location,"London, UK","[UK, London]",Wise,Adzuna::API::Response::Company
4,2026-08-28T09:16:41Z,Adzuna::API::Response::Job,part_time,-0.162653,22880.00,We're looking for English speakers located any...,Data Analyst (AI Training),51.410300,https://www.adzuna.co.uk/jobs/land/ad/58594925...,0,...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTg1OTQ5MjUxMCIsI...,permanent,part-time-jobs,Part time Jobs,Adzuna::API::Response::Category,Adzuna::API::Response::Location,"Furzedown, South West London","[UK, London, South West London, Furzedown]",OneForma,Adzuna::API::Response::Company

## 5. Inspect DataFrame Columns

The normalized DataFrame contains 22 columns. We will inspect the available fields and identify the variables required for job-market analysis.

In [9]:
df.columns.tolist()

['created',
 '__CLASS__',
 'contract_time',
 'longitude',
 'salary_min',
 'description',
 'title',
 'latitude',
 'redirect_url',
 'salary_is_predicted',
 'id',
 'salary_max',
 'adref',
 'contract_type',
 'category.tag',
 'category.label',
 'category.__CLASS__',
 'location.__CLASS__',
 'location.display_name',
 'location.area',
 'company.display_name',
 'company.__CLASS__']

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   created                10 non-null     str
 1   __CLASS__              10 non-null     str
 2   contract_time          10 non-null     str
 3   longitude              10 non-null     float64
 4   salary_min             10 non-null     float64
 5   description            10 non-null     str
 6   title                  10 non-null     str
 7   latitude               10 non-null     float64
 8   redirect_url           10 non-null     str
 9   salary_is_predicted    10 non-null     str
 10  id                     10 non-null     str
 11  salary_max             10 non-null     float64
 12  adref                  10 non-null     str
 13  contract_type          6 non-null      str
 14  category.tag           10 non-null     str
 15  category.label         10 non-null     str
 16  category.__CLASS__     10 non-null     str
 17  location.__CLASS__     10 non-null     str
 18  location.display_name  10 non-null     str
 19  location.area          10 non-null     object
 20  company.display_name   10 non-null     str
 21  company.__CLASS__      10 non-null     str
dtypes: float64(4), object(1), str(17)
memory usage: 1.8+ KB

In [11]:
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

1. created
2. __CLASS__
3. contract_time
4. longitude
5. salary_min
6. description
7. title
8. latitude
9. redirect_url
10. salary_is_predicted
11. id
12. salary_max
13. adref
14. contract_type
15. category.tag
16. category.label
17. category.__CLASS__
18. location.__CLASS__
19. location.display_name
20. location.area
21. company.display_name
22. company.__CLASS__

## 6. Assess Missing Values and Data Types

Before selecting the analytical fields, we will assess missing values and data types to understand the quality and structure of the API data.

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   created                10 non-null     str
 1   __CLASS__              10 non-null     str
 2   contract_time          10 non-null     str
 3   longitude              10 non-null     float64
 4   salary_min             10 non-null     float64
 5   description            10 non-null     str
 6   title                  10 non-null     str
 7   latitude               10 non-null     float64
 8   redirect_url           10 non-null     str
 9   salary_is_predicted    10 non-null     str
 10  id                     10 non-null     str
 11  salary_max             10 non-null     float64
 12  adref                  10 non-null     str
 13  contract_type          6 non-null      str
 14  category.tag           10 non-null     str
 15  category.label         10 non-null     str
 16  category.__CLASS__     10 non-null     str
 17  location.__CLASS__     10 non-null     str
 18  location.display_name  10 non-null     str
 19  location.area          10 non-null     object
 20  company.display_name   10 non-null     str
 21  company.__CLASS__      10 non-null     str
dtypes: float64(4), object(1), str(17)
memory usage: 1.8+ KB

In [13]:
df.isna().sum().sort_values(ascending=False)

contract_type            4
created                  0
contract_time            0
longitude                0
salary_min               0
__CLASS__                0
description              0
title                    0
redirect_url             0
latitude                 0
salary_is_predicted      0
id                       0
salary_max               0
adref                    0
category.tag             0
category.label           0
category.__CLASS__       0
location.__CLASS__       0
location.display_name    0
location.area            0
company.display_name     0
company.__CLASS__        0
dtype: int64

In [14]:
df.dtypes

created                      str
__CLASS__                    str
contract_time                str
longitude                float64
salary_min               float64
description                  str
title                        str
latitude                 float64
redirect_url                 str
salary_is_predicted          str
id                           str
salary_max               float64
adref                        str
contract_type                str
category.tag                 str
category.label               str
category.__CLASS__           str
location.__CLASS__           str
location.display_name        str
location.area             object
company.display_name         str
company.__CLASS__            str
dtype: object

## 7. Missing-Value Summary

We will quantify missing values in each field to determine which columns require cleaning or special handling.

In [15]:
missing_summary = (
    df.isna()
      .sum()
      .to_frame("missing_count")
      .assign(
          missing_pct=lambda x: (x["missing_count"] / len(df) * 100).round(1)
      )
      .sort_values("missing_count", ascending=False)
)

missing_summary

                       missing_count  missing_pct
contract_type                      4         40.0
created                            0          0.0
contract_time                      0          0.0
longitude                          0          0.0
salary_min                         0          0.0
__CLASS__                          0          0.0
description                        0          0.0
title                              0          0.0
redirect_url                       0          0.0
latitude                           0          0.0
salary_is_predicted                0          0.0
id                                 0          0.0
salary_max                         0          0.0
adref                              0          0.0
category.tag                       0          0.0
category.label                     0          0.0
category.__CLASS__                 0          0.0
location.__CLASS__                 0          0.0
location.display_name              0          0.0
location.area                      0          0.0
company.display_name               0          0.0
company.__CLASS__                  0          0.0

In [16]:
df["location.area"].head().tolist()

[['UK', 'London'],
 ['UK', 'London'],
 ['UK', 'London'],
 ['UK', 'London'],
 ['UK', 'London', 'South West London', 'Furzedown']]

## 8. Select Analytical Fields

We will retain the fields needed for job-market, salary, location, employment, and skills analysis while removing API-specific technical metadata.

In [17]:
selected_columns = [
    "id",
    "title",
    "company.display_name",
    "location.display_name",
    "location.area",
    "category.label",
    "contract_type",
    "contract_time",
    "salary_min",
    "salary_max",
    "salary_is_predicted",
    "created",
    "description",
    "redirect_url"
]

jobs_df = df[selected_columns].copy()

print("Shape:", jobs_df.shape)
jobs_df.head()

Shape: (10, 14)

,id,title,company.display_name,location.display_name,location.area,category.label,contract_type,contract_time,salary_min,salary_max,salary_is_predicted,created,description,redirect_url
0,5838381458,Lead Data Analyst,Wise,"London, UK","[UK, London]",Accounting & Finance Jobs,contract,full_time,71829.23,71829.23,1,2026-08-12T15:38:55Z,"Wise is a global technology company, building ...",https://www.adzuna.co.uk/jobs/land/ad/58383814...
1,5879749780,Data Analyst,Anson Mccade,"London, UK","[UK, London]",IT Jobs,permanent,full_time,49156.57,49156.57,1,2026-09-11T13:56:37Z,"£45,000 - 60,000 GBP Pension, Benefits Hybrid ...",https://www.adzuna.co.uk/jobs/land/ad/58797497...
2,5861182353,Risk Technology Data Analyst,BGC Partners,"London, UK","[UK, London]",IT Jobs,NaN,full_time,46263.40,46263.40,1,2026-08-29T15:29:41Z,The Risk Technology Data Analyst will be a key...,https://www.adzuna.co.uk/jobs/land/ad/58611823...
3,5838383439,"Staff Data Analyst, Operations",Wise,"London, UK","[UK, London]",IT Jobs,contract,full_time,88466.81,88466.81,1,2026-08-12T15:39:11Z,"Wise is a global technology company, building ...",https://www.adzuna.co.uk/jobs/land/ad/58383834...
4,5859492510,Data Analyst (AI Training),OneForma,"Furzedown, South West London","[UK, London, South West London, Furzedown]",Part time Jobs,permanent,part_time,22880.00,22880.00,0,2026-08-28T09:16:41Z,We're looking for English speakers located any...,https://www.adzuna.co.uk/jobs/land/ad/58594925...

In [18]:
jobs_df["country"] = jobs_df["location.area"].apply(
    lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None
)

jobs_df["city"] = jobs_df["location.area"].apply(
    lambda x: x[-1] if isinstance(x, list) and len(x) > 1 else None
)

jobs_df[["location.area", "country", "city"]].head()

                                location.area country       city
0                                [UK, London]      UK     London
1                                [UK, London]      UK     London
2                                [UK, London]      UK     London
3                                [UK, London]      UK     London
4  [UK, London, South West London, Furzedown]      UK  Furzedown

In [19]:
jobs_df["created"] = pd.to_datetime(
    jobs_df["created"],
    errors="coerce",
    utc=True
)

jobs_df["salary_is_predicted"] = (
    jobs_df["salary_is_predicted"]
    .astype(str)
    .str.lower()
    .map({"true": True, "false": False})
)

jobs_df[["created", "salary_is_predicted"]].head()

                    created salary_is_predicted
0 2026-08-12 15:38:55+00:00                 NaN
1 2026-09-11 13:56:37+00:00                 NaN
2 2026-08-29 15:29:41+00:00                 NaN
3 2026-08-12 15:39:11+00:00                 NaN
4 2026-08-28 09:16:41+00:00                 NaN

In [20]:
jobs_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     10 non-null     str
 1   title                  10 non-null     str
 2   company.display_name   10 non-null     str
 3   location.display_name  10 non-null     str
 4   location.area          10 non-null     object
 5   category.label         10 non-null     str
 6   contract_type          6 non-null      str
 7   contract_time          10 non-null     str
 8   salary_min             10 non-null     float64
 9   salary_max             10 non-null     float64
 10  salary_is_predicted    0 non-null      object
 11  created                10 non-null     datetime64[us, UTC]
 12  description            10 non-null     str
 13  redirect_url           10 non-null     str
 14  country                10 non-null     str
 15  city                   10 non-null     str
dtypes: datetime64[us, UTC](1), float64(2), object(2), str(11)
memory usage: 1.4+ KB

## 9. Inspect Salary Prediction Flag

The salary prediction field did not convert successfully. We will inspect its original values before applying the correct transformation.

In [21]:
df["salary_is_predicted"].value_counts(dropna=False)

salary_is_predicted
1    8
0    2
Name: count, dtype: int64

## 10. Correct Salary Prediction Flag

Adzuna returns the salary prediction indicator as numeric values. We will convert it to a boolean field where `1` indicates a predicted salary and `0` indicates a non-predicted salary.

In [22]:
jobs_df["salary_is_predicted"] = (
    df["salary_is_predicted"]
    .astype(int)
    .astype(bool)
)

jobs_df["salary_is_predicted"].value_counts()

salary_is_predicted
True     8
False    2
Name: count, dtype: int64

In [23]:
jobs_df[["salary_min", "salary_max", "salary_is_predicted"]].head(10)

   salary_min  salary_max  salary_is_predicted
0    71829.23    71829.23                 True
1    49156.57    49156.57                 True
2    46263.40    46263.40                 True
3    88466.81    88466.81                 True
4    22880.00    22880.00                False
5    72841.98    72841.98                 True
6    47855.71    47855.71                 True
7    52152.68    52152.68                 True
8    49846.42    49846.42                 True
9    40000.00    85000.00                False

## 11. Clean Salary Prediction Flag

Adzuna returns the salary prediction indicator as `0` or `1`. We convert it to a boolean field for analysis.

In [24]:
jobs_df["salary_is_predicted"] = (
    df["salary_is_predicted"]
    .astype(int)
    .astype(bool)
)

jobs_df["salary_is_predicted"].value_counts()

salary_is_predicted
True     8
False    2
Name: count, dtype: int64

## 12. Inspect Contract Type

Contract type contains missing values. We will inspect the available categories before deciding how to handle missing entries.

In [25]:
jobs_df["contract_type"].value_counts(dropna=False)

contract_type
contract     4
NaN          4
permanent    2
Name: count, dtype: int64

## 13. Assess Salary Coverage

We will check how many listings contain usable minimum and maximum salary information before performing salary analysis.

In [26]:
salary_summary = pd.DataFrame({
    "salary_min_present": [jobs_df["salary_min"].notna().sum()],
    "salary_max_present": [jobs_df["salary_max"].notna().sum()],
    "both_present": [
        jobs_df["salary_min"].notna().sum()
        and jobs_df["salary_max"].notna().sum()
    ]
})

salary_summary

   salary_min_present  salary_max_present  both_present
0                  10                  10            10

In [27]:
salary_summary = {
    "total_jobs": len(jobs_df),
    "salary_min_present": jobs_df["salary_min"].notna().sum(),
    "salary_max_present": jobs_df["salary_max"].notna().sum(),
    "both_salary_values_present": (
        jobs_df["salary_min"].notna() &
        jobs_df["salary_max"].notna()
    ).sum()
}

salary_summary

{'total_jobs': 10,
 'salary_min_present': np.int64(10),
 'salary_max_present': np.int64(10),
 'both_salary_values_present': np.int64(10)}

In [28]:
jobs_df[["salary_min", "salary_max", "salary_is_predicted"]].describe()

         salary_min    salary_max
count     10.000000     10.000000
mean   54129.280000  58629.280000
std    18758.348726  20324.439646
min    22880.000000  22880.000000
25%    46661.477500  48180.925000
50%    49501.495000  50999.550000
75%    66910.092500  72588.792500
max    88466.810000  88466.810000

## 14. Inspect Salary Prediction Coverage

We will examine how many job listings contain salaries reported directly by employers versus salaries estimated by the API.

In [29]:
jobs_df["salary_is_predicted"].value_counts(dropna=False)

salary_is_predicted
True     8
False    2
Name: count, dtype: int64

## 15. Inspect Contract Type

We will examine the available contract types and identify missing values before deciding how to handle them.

In [30]:
jobs_df["contract_type"].value_counts(dropna=False)

contract_type
contract     4
NaN          4
permanent    2
Name: count, dtype: int64

## 16. Inspect Contract Time

We will examine the available contract-time categories and identify missing values before preparing the dataset for analysis.

In [31]:
jobs_df["contract_time"].value_counts(dropna=False)

contract_time
full_time    9
part_time    1
Name: count, dtype: int64

## 17. Inspect Job Categories

We will examine the job categories returned by the API to understand how the listings are classified.

In [32]:
jobs_df["category.label"].value_counts(dropna=False)

category.label
IT Jobs                             7
Accounting & Finance Jobs           1
Part time Jobs                      1
PR, Advertising & Marketing Jobs    1
Name: count, dtype: int64

## 18. Inspect Job Locations

We will examine the locations returned by the API to verify the geographic coverage of the collected listings.

In [33]:
jobs_df["location.display_name"].value_counts(dropna=False)

location.display_name
London, UK                      9
Furzedown, South West London    1
Name: count, dtype: int64

## 19. Inspect Job Titles

We will examine the job titles returned by the API to understand the variation within the "data analyst" search results.

In [34]:
jobs_df["title"].value_counts(dropna=False)

title
Data Analyst                                     3
Lead Data Analyst                                1
Risk Technology Data Analyst                     1
Staff Data Analyst, Operations                   1
Data Analyst (AI Training)                       1
Market Data Analyst AVP                          1
Senior Product Data Analyst - Consumer Growth    1
Data Analysts                                    1
Name: count, dtype: int64

## 20. Inspect Hiring Companies

We will examine the companies associated with the collected job listings to understand employer demand within the API response.

In [35]:
jobs_df["company.display_name"].value_counts(dropna=False)

company.display_name
Wise               2
Anson Mccade       1
BGC Partners       1
OneForma           1
Hunter Bond        1
SumUp              1
Robert Half        1
BDO Recruitment    1
Solirius Reply     1
Name: count, dtype: int64

## 21. Validate Salary Ranges

We will check whether the reported minimum salary is consistently less than or equal to the maximum salary before using salary fields for analysis.

In [36]:
salary_check = (
    jobs_df["salary_min"] <= jobs_df["salary_max"]
)

print("Valid salary ranges:", salary_check.sum())
print("Invalid salary ranges:", (~salary_check).sum())

Valid salary ranges: 10
Invalid salary ranges: 0

## 22. Inspect Job Posting Dates

We will examine the date range of the collected listings to verify when the returned jobs were posted.

In [37]:
print("Earliest posting:", jobs_df["created"].min())
print("Latest posting:", jobs_df["created"].max())

Earliest posting: 2026-05-22 11:06:12+00:00
Latest posting: 2026-09-11 13:56:37+00:00

## 23. Check for Duplicate Job Listings

We will verify whether the API response contains duplicate job IDs before building the final dataset.

In [38]:
duplicate_ids = jobs_df["id"].duplicated().sum()

print("Duplicate job IDs:", duplicate_ids)
print("Unique job IDs:", jobs_df["id"].nunique())
print("Total job listings:", len(jobs_df))

Duplicate job IDs: 0
Unique job IDs: 10
Total job listings: 10

## 24. Inspect Job Description Content

Job descriptions will be used later to identify in-demand technical and analytical skills. We will inspect their length and availability before designing the skills-extraction process.

In [39]:
description_summary = {
    "total_jobs": len(jobs_df),
    "descriptions_present": jobs_df["description"].notna().sum(),
    "descriptions_empty": (jobs_df["description"].fillna("").str.strip() == "").sum(),
    "average_description_length": jobs_df["description"].fillna("").str.len().mean(),
    "minimum_description_length": jobs_df["description"].fillna("").str.len().min(),
    "maximum_description_length": jobs_df["description"].fillna("").str.len().max()
}

description_summary

{'total_jobs': 10,
 'descriptions_present': np.int64(10),
 'descriptions_empty': np.int64(0),
 'average_description_length': np.float64(500.0),
 'minimum_description_length': np.int64(500),
 'maximum_description_length': np.int64(500)}

In [40]:
jobs_df[["title", "description"]].head(3)

,title,description
0,Lead Data Analyst,"Wise is a global technology company, building ..."
1,Data Analyst,"£45,000 - 60,000 GBP Pension, Benefits Hybrid ..."
2,Risk Technology Data Analyst,The Risk Technology Data Analyst will be a key...

## 25. Inspect Description Snippets

We will display complete description snippets to determine whether technical skills and tools are identifiable from the API-provided text.

In [41]:
for i, row in jobs_df.head(3).iterrows():
    print(f"\n{'=' * 80}")
    print(f"JOB {i + 1}: {row['title']}")
    print(f"{'=' * 80}")
    print(row["description"])

================================================================================
JOB 1: Lead Data Analyst
================================================================================
Wise is a global technology company, building the best way to move and manage the world’s money. Min fees. Max ease. Full speed. Whether people and businesses are sending money to another country, spending abroad, or making and receiving international payments, Wise is on a mission to make their lives easier and save them money. As part of our team, you will be helping us create an entirely new network for the worlds money. For everyone, everywhere. Job Description We are looking for a Lead Dat…

================================================================================
JOB 2: Data Analyst
================================================================================
£45,000 - 60,000 GBP Pension, Benefits Hybrid WORKING Location: Central London, Greater London - United Kingdom Type: Permanent Data Analyst (Reporting & Visualisation) Data & Digital Transformation Location: London / Hybrid Working Salary: Up to £60,000  Benefits Package About the Role We're supporting a leading transformation consultancy looking to expand its Data & Technology practice with the addition of a Data Analyst specialising in Reporting & Visualisation. This is an excellent opportun…

================================================================================
JOB 3: Risk Technology Data Analyst
================================================================================
The Risk Technology Data Analyst will be a key member of the Risk Management Technology team, contributing to the development and enhancement of risk systems. This role offers an opportunity to work with a dynamic team, utilizing cutting-edge technologies to manage and mitigate risks across the enterprise. Responsibilities Collaborate with Risk Management to gather and analyze requirements for risk systems. Build and enhance data analysis processes, including asset valuations and custom measure…

## 26. Build a Reusable API Collection Function

We will create a reusable function to collect multiple pages of job listings from the Adzuna API. This will allow us to scale the test request into a structured job-market dataset while keeping the API collection process reproducible.

In [42]:
def fetch_adzuna_jobs(
    query,
    location="",
    pages=3,
    results_per_page=50
):
    """
    Fetch multiple pages of job listings from the Adzuna API.
    """

    all_jobs = []

    for page in range(1, pages + 1):

        url = f"https://api.adzuna.com/v1/api/jobs/gb/search/{page}"

        params = {
            "app_id": APP_ID,
            "app_key": APP_KEY,
            "what": query,
            "where": location,
            "results_per_page": results_per_page,
            "content-type": "application/json"
        }

        response = requests.get(
            url,
            params=params,
            timeout=30
        )

        print(
            f"Query: {query} | "
            f"Location: {location} | "
            f"Page: {page} | "
            f"Status: {response.status_code}"
        )

        response.raise_for_status()

        page_data = response.json()

        all_jobs.extend(page_data.get("results", []))

    return all_jobs

## 27. Test the Collection Function

We will test the reusable function with the existing Data Analyst and London search before collecting the full dataset.

In [43]:
test_jobs = fetch_adzuna_jobs(
    query="data analyst",
    location="London",
    pages=2,
    results_per_page=10
)

print("Jobs collected:", len(test_jobs))

Query: data analyst | Location: London | Page: 1 | Status: 200
Query: data analyst | Location: London | Page: 2 | Status: 200
Jobs collected: 20

## 28. Define the Project 10 Collection Plan

We will collect job listings across multiple job roles and major UK locations to create a diverse dataset for job-market and skills analysis.

The collection will use multiple API pages for each role-location combination, then deduplicate listings using the Adzuna job ID.

In [44]:
search_queries = [
    "data analyst",
    "data scientist",
    "business analyst",
    "machine learning engineer",
    "business intelligence analyst",
    "python developer"
]

locations = [
    "London",
    "Manchester",
    "Birmingham"
]

pages_per_search = 2
results_per_page = 50

total_requests = (
    len(search_queries)
    * len(locations)
    * pages_per_search
)

print("Job roles:", len(search_queries))
print("Locations:", len(locations))
print("Pages per search:", pages_per_search)
print("Results per page:", results_per_page)
print("Maximum API requests:", total_requests)

Job roles: 6
Locations: 3
Pages per search: 2
Results per page: 50
Maximum API requests: 36

## 29. Collect Job-Market Data

We will collect job listings for six role categories across London, Manchester, and Birmingham. A short delay between requests will help keep the collection within the API rate limits.

In [45]:
import time
import json
from pathlib import Path

all_jobs = []

for query in search_queries:
    for location in locations:

        print(f"\n{'=' * 70}")
        print(f"Collecting: {query} | {location}")
        print(f"{'=' * 70}")

        jobs = fetch_adzuna_jobs(
            query=query,
            location=location,
            pages=pages_per_search,
            results_per_page=results_per_page
        )

        all_jobs.extend(jobs)

        print(f"Collected for this search: {len(jobs)}")

        time.sleep(2.5)

print("\nTotal raw listings collected:", len(all_jobs))

======================================================================
Collecting: data analyst | London
======================================================================
Query: data analyst | Location: London | Page: 1 | Status: 200
Query: data analyst | Location: London | Page: 2 | Status: 200
Collected for this search: 100

======================================================================
Collecting: data analyst | Manchester
======================================================================
Query: data analyst | Location: Manchester | Page: 1 | Status: 200
Query: data analyst | Location: Manchester | Page: 2 | Status: 200
Collected for this search: 73

======================================================================
Collecting: data analyst | Birmingham
======================================================================
Query: data analyst | Location: Birmingham | Page: 1 | Status: 200
Query: data analyst | Location: Birmingham | Page: 2 | Status: 200
Collected for this search: 27

======================================================================
Collecting: data scientist | London
======================================================================
Query: data scientist | Location: London | Page: 1 | Status: 200
Query: data scientist | Location: London | Page: 2 | Status: 200
Collected for this search: 100

======================================================================
Collecting: data scientist | Manchester
======================================================================
Query: data scientist | Location: Manchester | Page: 1 | Status: 200
Query: data scientist | Location: Manchester | Page: 2 | Status: 200
Collected for this search: 100

======================================================================
Collecting: data scientist | Birmingham
======================================================================
Query: data scientist | Location: Birmingham | Page: 1 | Status: 200
Query: data scientist | Location: Birmingham | Page: 2 | Status: 200
Collected for this search: 61

======================================================================
Collecting: business analyst | London
======================================================================
Query: business analyst | Location: London | Page: 1 | Status: 200
Query: business analyst | Location: London | Page: 2 | Status: 200
Collected for this search: 100

======================================================================
Collecting: business analyst | Manchester
======================================================================
Query: business analyst | Location: Manchester | Page: 1 | Status: 200
Query: business analyst | Location: Manchester | Page: 2 | Status: 200
Collected for this search: 95

======================================================================
Collecting: business analyst | Birmingham
======================================================================
Query: business analyst | Location: Birmingham | Page: 1 | Status: 200
Query: business analyst | Location: Birmingham | Page: 2 | Status: 200
Collected for this search: 77

======================================================================
Collecting: machine learning engineer | London
======================================================================
Query: machine learning engineer | Location: London | Page: 1 | Status: 200
Query: machine learning engineer | Location: London | Page: 2 | Status: 200
Collected for this search: 100

======================================================================
Collecting: machine learning engineer | Manchester
======================================================================
Query: machine learning engineer | Location: Manchester | Page: 1 | Status: 200
Query: machine learning engineer | Location: Manchester | Page: 2 | Status: 200
Collected for this search: 23

======================================================================
Collecting: machine learning engineer | Birmingham
======================================================================
Query: machine learning engineer | Location: Birmingham | Page: 1 | Status: 200
Query: machine learning engineer | Location: Birmingham | Page: 2 | Status: 200
Collected for this search: 6

======================================================================
Collecting: business intelligence analyst | London
======================================================================
Query: business intelligence analyst | Location: London | Page: 1 | Status: 200
Query: business intelligence analyst | Location: London | Page: 2 | Status: 200
Collected for this search: 32

======================================================================
Collecting: business intelligence analyst | Manchester
======================================================================
Query: business intelligence analyst | Location: Manchester | Page: 1 | Status: 200
Query: business intelligence analyst | Location: Manchester | Page: 2 | Status: 200
Collected for this search: 7

======================================================================
Collecting: business intelligence analyst | Birmingham
======================================================================
Query: business intelligence analyst | Location: Birmingham | Page: 1 | Status: 200
Query: business intelligence analyst | Location: Birmingham | Page: 2 | Status: 200
Collected for this search: 9

======================================================================
Collecting: python developer | London
======================================================================
Query: python developer | Location: London | Page: 1 | Status: 200
Query: python developer | Location: London | Page: 2 | Status: 200
Collected for this search: 100

======================================================================
Collecting: python developer | Manchester
======================================================================
Query: python developer | Location: Manchester | Page: 1 | Status: 200
Query: python developer | Location: Manchester | Page: 2 | Status: 200
Collected for this search: 62

======================================================================
Collecting: python developer | Birmingham
======================================================================
Query: python developer | Location: Birmingham | Page: 1 | Status: 200
Query: python developer | Location: Birmingham | Page: 2 | Status: 200
Collected for this search: 17

Total raw listings collected: 1089

## 30. Save Complete Raw Dataset

We will save the complete API response as a raw JSON snapshot so the original collected data is preserved before cleaning and transformation.

In [46]:
raw_dataset_path = "../data/raw/adzuna_project10_raw.json"

with open(raw_dataset_path, "w", encoding="utf-8") as file:
    json.dump(
        all_jobs,
        file,
        indent=2,
        ensure_ascii=False
    )

print(f"Raw dataset saved to: {raw_dataset_path}")
print(f"Raw listings saved: {len(all_jobs)}")

Raw dataset saved to: ../data/raw/adzuna_project10_raw.json
Raw listings saved: 1089

## 31. Normalize the Full API Dataset

We will convert the collected JSON job listings into a pandas DataFrame so the dataset can be cleaned, deduplicated, and prepared for SQL analysis.

In [47]:
jobs_raw_df = pd.json_normalize(all_jobs)

print("Raw DataFrame shape:", jobs_raw_df.shape)
jobs_raw_df.head()

Raw DataFrame shape: (1089, 22)

,created,description,contract_time,contract_type,salary_min,redirect_url,adref,__CLASS__,title,longitude,...,salary_is_predicted,id,category.label,category.__CLASS__,category.tag,company.display_name,company.__CLASS__,location.display_name,location.__CLASS__,location.area
0,2026-08-12T15:38:55Z,"Wise is a global technology company, building ...",full_time,contract,71829.23,https://www.adzuna.co.uk/jobs/land/ad/58383814...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgzODM4MTQ1OCIsI...,Adzuna::API::Response::Job,Lead Data Analyst,-0.139134,...,1,5838381458,Accounting & Finance Jobs,Adzuna::API::Response::Category,accounting-finance-jobs,Wise,Adzuna::API::Response::Company,"London, UK",Adzuna::API::Response::Location,"[UK, London]"
1,2026-09-11T13:56:37Z,"£45,000 - 60,000 GBP Pension, Benefits Hybrid ...",full_time,permanent,49156.57,https://www.adzuna.co.uk/jobs/land/ad/58797497...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiMExsdjFIV3Y4UkdlW...,Adzuna::API::Response::Job,Data Analyst,-0.139134,...,1,5879749780,IT Jobs,Adzuna::API::Response::Category,it-jobs,Anson Mccade,Adzuna::API::Response::Company,"London, UK",Adzuna::API::Response::Location,"[UK, London]"
2,2026-08-29T15:29:41Z,The Risk Technology Data Analyst will be a key...,full_time,NaN,46263.40,https://www.adzuna.co.uk/jobs/land/ad/58611823...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTg2MTE4MjM1MyIsI...,Adzuna::API::Response::Job,Risk Technology Data Analyst,-0.139134,...,1,5861182353,IT Jobs,Adzuna::API::Response::Category,it-jobs,BGC Partners,Adzuna::API::Response::Company,"London, UK",Adzuna::API::Response::Location,"[UK, London]"
3,2026-08-12T15:39:11Z,"Wise is a global technology company, building ...",full_time,contract,88466.81,https://www.adzuna.co.uk/jobs/land/ad/58383834...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiMExsdjFIV3Y4UkdlW...,Adzuna::API::Response::Job,"Staff Data Analyst, Operations",-0.139134,...,1,5838383439,IT Jobs,Adzuna::API::Response::Category,it-jobs,Wise,Adzuna::API::Response::Company,"London, UK",Adzuna::API::Response::Location,"[UK, London]"
4,2026-08-28T09:16:41Z,We're looking for English speakers located any...,part_time,permanent,22880.00,https://www.adzuna.co.uk/jobs/land/ad/58594925...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTg1OTQ5MjUxMCIsI...,Adzuna::API::Response::Job,Data Analyst (AI Training),-0.162653,...,0,5859492510,Part time Jobs,Adzuna::API::Response::Category,part-time-jobs,OneForma,Adzuna::API::Response::Company,"Furzedown, South West London",Adzuna::API::Response::Location,"[UK, London, South West London, Furzedown]"

## 32. Check Duplicate Listings

The same job listing may appear in multiple role or location searches. We will identify duplicates using the unique Adzuna job ID.

In [48]:
duplicate_count = jobs_raw_df["id"].duplicated().sum()
unique_job_count = jobs_raw_df["id"].nunique()

print("Total raw listings:", len(jobs_raw_df))
print("Unique job IDs:", unique_job_count)
print("Duplicate listings:", duplicate_count)

Total raw listings: 1089
Unique job IDs: 986
Duplicate listings: 103

## 33. Create Deduplicated Master Dataset

We will remove duplicate listings using the unique Adzuna job ID while preserving the first occurrence of each job.

In [49]:
jobs_df = (
    jobs_raw_df
    .drop_duplicates(subset="id", keep="first")
    .reset_index(drop=True)
)

print("Raw listings:", len(jobs_raw_df))
print("Deduplicated listings:", len(jobs_df))
print("Removed duplicates:", len(jobs_raw_df) - len(jobs_df))

Raw listings: 1089
Deduplicated listings: 986
Removed duplicates: 103

In [50]:
jobs_df.head()

,created,description,contract_time,contract_type,salary_min,redirect_url,adref,__CLASS__,title,longitude,...,salary_is_predicted,id,category.label,category.__CLASS__,category.tag,company.display_name,company.__CLASS__,location.display_name,location.__CLASS__,location.area
0,2026-08-12T15:38:55Z,"Wise is a global technology company, building ...",full_time,contract,71829.23,https://www.adzuna.co.uk/jobs/land/ad/58383814...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTgzODM4MTQ1OCIsI...,Adzuna::API::Response::Job,Lead Data Analyst,-0.139134,...,1,5838381458,Accounting & Finance Jobs,Adzuna::API::Response::Category,accounting-finance-jobs,Wise,Adzuna::API::Response::Company,"London, UK",Adzuna::API::Response::Location,"[UK, London]"
1,2026-09-11T13:56:37Z,"£45,000 - 60,000 GBP Pension, Benefits Hybrid ...",full_time,permanent,49156.57,https://www.adzuna.co.uk/jobs/land/ad/58797497...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiMExsdjFIV3Y4UkdlW...,Adzuna::API::Response::Job,Data Analyst,-0.139134,...,1,5879749780,IT Jobs,Adzuna::API::Response::Category,it-jobs,Anson Mccade,Adzuna::API::Response::Company,"London, UK",Adzuna::API::Response::Location,"[UK, London]"
2,2026-08-29T15:29:41Z,The Risk Technology Data Analyst will be a key...,full_time,NaN,46263.40,https://www.adzuna.co.uk/jobs/land/ad/58611823...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTg2MTE4MjM1MyIsI...,Adzuna::API::Response::Job,Risk Technology Data Analyst,-0.139134,...,1,5861182353,IT Jobs,Adzuna::API::Response::Category,it-jobs,BGC Partners,Adzuna::API::Response::Company,"London, UK",Adzuna::API::Response::Location,"[UK, London]"
3,2026-08-12T15:39:11Z,"Wise is a global technology company, building ...",full_time,contract,88466.81,https://www.adzuna.co.uk/jobs/land/ad/58383834...,eyJhbGciOiJIUzI1NiJ9.eyJzIjoiMExsdjFIV3Y4UkdlW...,Adzuna::API::Response::Job,"Staff Data Analyst, Operations",-0.139134,...,1,5838383439,IT Jobs,Adzuna::API::Response::Category,it-jobs,Wise,Adzuna::API::Response::Company,"London, UK",Adzuna::API::Response::Location,"[UK, London]"
4,2026-08-28T09:16:41Z,We're looking for English speakers located any...,part_time,permanent,22880.00,https://www.adzuna.co.uk/jobs/land/ad/58594925...,eyJhbGciOiJIUzI1NiJ9.eyJpIjoiNTg1OTQ5MjUxMCIsI...,Adzuna::API::Response::Job,Data Analyst (AI Training),-0.162653,...,0,5859492510,Part time Jobs,Adzuna::API::Response::Category,part-time-jobs,OneForma,Adzuna::API::Response::Company,"Furzedown, South West London",Adzuna::API::Response::Location,"[UK, London, South West London, Furzedown]"

## 34. Standardize Column Names

We will rename nested API field names into clean, database-friendly column names. This will make the dataset easier to work with in PostgreSQL, SQL, and Power BI.

In [51]:
jobs_df = jobs_df.rename(columns={
    "company.display_name": "company",
    "location.display_name": "location",
    "location.area": "location_area",
    "category.label": "category",
    "category.tag": "category_tag",
    "contract_type": "contract_type",
    "contract_time": "contract_time",
    "salary_min": "salary_min",
    "salary_max": "salary_max",
    "salary_is_predicted": "salary_is_predicted"
})

print("Columns:")
print(jobs_df.columns.tolist())

Columns:
['created', 'description', 'contract_time', 'contract_type', 'salary_min', 'redirect_url', 'adref', '__CLASS__', 'title', 'longitude', 'latitude', 'salary_max', 'salary_is_predicted', 'id', 'category', 'category.__CLASS__', 'category_tag', 'company', 'company.__CLASS__', 'location', 'location.__CLASS__', 'location_area']

## 35. Clean Location Fields

We will extract country and city information from the nested location-area field returned by the API.

In [52]:
jobs_df["country"] = jobs_df["location_area"].apply(
    lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None
)

jobs_df["city"] = jobs_df["location_area"].apply(
    lambda x: x[-1] if isinstance(x, list) and len(x) > 1 else None
)

jobs_df[["location", "location_area", "country", "city"]].head(10)

,location,location_area,country,city
0,"London, UK","[UK, London]",UK,London
1,"London, UK","[UK, London]",UK,London
2,"London, UK","[UK, London]",UK,London
3,"London, UK","[UK, London]",UK,London
4,"Furzedown, South West London","[UK, London, South West London, Furzedown]",UK,Furzedown
5,"London, UK","[UK, London]",UK,London
6,"London, UK","[UK, London]",UK,London
7,"London, UK","[UK, London]",UK,London
8,"London, UK","[UK, London]",UK,London
9,"London, UK","[UK, London]",UK,London

## 36. Standardize Job Posting Dates

We will ensure the job posting timestamp is stored consistently as a timezone-aware datetime for time-based analysis.

In [53]:
jobs_df["created"] = pd.to_datetime(
    jobs_df["created"],
    errors="coerce",
    utc=True
)

print("Missing posting dates:", jobs_df["created"].isna().sum())
print("Earliest posting:", jobs_df["created"].min())
print("Latest posting:", jobs_df["created"].max())

Missing posting dates: 0
Earliest posting: 2023-12-28 17:21:08+00:00
Latest posting: 2026-09-13 12:46:53+00:00

## 37. Analyze Posting-Date Distribution

The collected dataset contains listings from different posting dates. We will examine the distribution by year and month before deciding whether a recency filter is appropriate.

In [54]:
jobs_df["posting_year"] = jobs_df["created"].dt.year
jobs_df["posting_month"] = jobs_df["created"].dt.to_period("M").astype(str)

print("Listings by year:")
print(jobs_df["posting_year"].value_counts().sort_index())

print("\nListings by month:")
print(jobs_df["posting_month"].value_counts().sort_index())

Listings by year:
posting_year
2023      2
2024      2
2025     32
2026    950
Name: count, dtype: int64

Listings by month:
posting_month
2023-12      2
2024-07      2
2025-01      2
2025-03      5
2025-07      3
2025-08      2
2025-09      4
2025-10      3
2025-11     10
2025-12      3
2026-01      7
2026-02     10
2026-03     19
2026-04     13
2026-05     34
2026-06     52
2026-07     96
2026-08    358
2026-09    361
Name: count, dtype: int64

C:\Users\dell\AppData\Local\Temp\ipykernel_2996\742995317.py:2: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  jobs_df["posting_month"] = jobs_df["created"].dt.to_period("M").astype(str)

## 38. Inspect Current-Year Posting Distribution

Most collected listings were posted in 2026. We will examine their monthly distribution to determine the appropriate recency window for the final job-market analysis.

In [55]:
current_year_jobs = jobs_df[
    jobs_df["posting_year"] == jobs_df["posting_year"].max()
]

print("Current year:", jobs_df["posting_year"].max())
print("Current-year listings:", len(current_year_jobs))
print("\nCurrent-year listings by month:")
print(
    current_year_jobs["posting_month"]
    .value_counts()
    .sort_index()
)

Current year: 2026
Current-year listings: 950

Current-year listings by month:
posting_month
2026-01      7
2026-02     10
2026-03     19
2026-04     13
2026-05     34
2026-06     52
2026-07     96
2026-08    358
2026-09    361
Name: count, dtype: int64

## 39. Create Current Job-Market Dataset

The raw dataset contains historical listings from 2023–2026. Because this project focuses on current job-market intelligence, the analytical dataset will use listings posted in 2026 while preserving the complete raw dataset separately.

In [56]:
jobs_df = jobs_df[
    jobs_df["posting_year"] == 2026
].copy()

jobs_df = jobs_df.reset_index(drop=True)

print("Current analytical listings:", len(jobs_df))
print("Earliest analytical posting:", jobs_df["created"].min())
print("Latest analytical posting:", jobs_df["created"].max())

Current analytical listings: 950
Earliest analytical posting: 2026-01-06 15:09:28+00:00
Latest analytical posting: 2026-09-13 12:46:53+00:00

In [57]:
jobs_df.shape

(950, 26)

## 40 — Prepare Analytical Columns

Prepare the current-year dataset for downstream skill extraction, SQL analysis, and dashboard development.

In [58]:
# Keep the core analytical fields for downstream processing

analytical_columns = [
    "id",
    "title",
    "company",
    "location",
    "country",
    "city",
    "category",
    "category_tag",
    "contract_type",
    "contract_time",
    "salary_min",
    "salary_max",
    "salary_is_predicted",
    "created",
    "posting_year",
    "posting_month",
    "description",
    "redirect_url"
]

jobs_analysis_df = jobs_df[analytical_columns].copy()

print("Analytical dataset shape:", jobs_analysis_df.shape)
print("\nMissing values:")
print(jobs_analysis_df.isna().sum())

Analytical dataset shape: (950, 18)

Missing values:
id                       0
title                    0
company                  0
location                 0
country                  0
city                     0
category                 0
category_tag             0
contract_type          604
contract_time          421
salary_min               0
salary_max               0
salary_is_predicted      0
created                  0
posting_year             0
posting_month            0
description              0
redirect_url             0
dtype: int64

## 41 — Standardize Employment Fields

Standardize missing employment information so the dataset can be analyzed consistently without removing valid job listings.

In [59]:
# Replace missing employment information with an explicit category

jobs_analysis_df["contract_type"] = (
    jobs_analysis_df["contract_type"]
    .fillna("unknown")
    .str.lower()
)

jobs_analysis_df["contract_time"] = (
    jobs_analysis_df["contract_time"]
    .fillna("unknown")
    .str.lower()
)

print("Contract type:")
print(jobs_analysis_df["contract_type"].value_counts())

print("\nContract time:")
print(jobs_analysis_df["contract_time"].value_counts())

Contract type:
contract_type
unknown      604
permanent    174
contract     172
Name: count, dtype: int64

Contract time:
contract_time
full_time    510
unknown      421
part_time     19
Name: count, dtype: int64

## 42 — Prepare Text for Skill Extraction

Prepare job titles and Adzuna-provided description snippets for automated skill extraction using an LLM API.

In [60]:
# Combine job title and description snippet for skill extraction

jobs_analysis_df["skill_extraction_text"] = (
    jobs_analysis_df["title"].fillna("")
    + ". "
    + jobs_analysis_df["description"].fillna("")
)

print("Rows prepared:", len(jobs_analysis_df))
print("Missing extraction text:", jobs_analysis_df["skill_extraction_text"].isna().sum())
print("\nSample:")
print(jobs_analysis_df["skill_extraction_text"].iloc[0])

Rows prepared: 950
Missing extraction text: 0

Sample:
Lead Data Analyst. Wise is a global technology company, building the best way to move and manage the world’s money. Min fees. Max ease. Full speed. Whether people and businesses are sending money to another country, spending abroad, or making and receiving international payments, Wise is on a mission to make their lives easier and save them money. As part of our team, you will be helping us create an entirely new network for the worlds money. For everyone, everywhere. Job Description We are looking for a Lead Dat…

## 43 — Build Skill Dictionary

Create a controlled skill dictionary for rule-based extraction from job titles and Adzuna-provided description snippets.

In [61]:
skill_dictionary = {
    "Programming": [
        "python",
        "r",
        "java",
        "javascript",
        "c++",
        "c#",
        "scala"
    ],
    "Data Analysis": [
        "pandas",
        "numpy",
        "scipy",
        "matplotlib",
        "statistics",
        "data analysis",
        "data analytics"
    ],
    "Databases & SQL": [
        "sql",
        "postgresql",
        "mysql",
        "sql server",
        "oracle",
        "mongodb",
        "database"
    ],
    "Business Intelligence": [
        "power bi",
        "tableau",
        "qlik",
        "looker",
        "business intelligence",
        "bi"
    ],
    "Cloud": [
        "aws",
        "azure",
        "google cloud",
        "gcp",
        "snowflake",
        "databricks"
    ],
    "Machine Learning": [
        "machine learning",
        "scikit-learn",
        "tensorflow",
        "pytorch",
        "deep learning",
        "nlp"
    ],
    "Data Engineering": [
        "spark",
        "pyspark",
        "etl",
        "data pipeline",
        "airflow",
        "hadoop"
    ],
    "Tools & Platforms": [
        "excel",
        "git",
        "github",
        "jira",
        "sap",
        "salesforce"
    ]
}

print("Skill categories:", len(skill_dictionary))
print("Total skill terms:", sum(len(v) for v in skill_dictionary.values()))

for category, skills in skill_dictionary.items():
    print(f"{category}: {len(skills)}")

Skill categories: 8
Total skill terms: 51
Programming: 7
Data Analysis: 7
Databases & SQL: 7
Business Intelligence: 6
Cloud: 6
Machine Learning: 6
Data Engineering: 6
Tools & Platforms: 6

## 44 — Extract Skills from Job Listings

Extract skills from job titles and Adzuna-provided description snippets using the controlled skill dictionary.

In [62]:
import re

def extract_skills(text, skill_dictionary):
    text = str(text).lower()
    found_skills = []

    for category, skills in skill_dictionary.items():
        for skill in skills:
            pattern = r"(?<!\w)" + re.escape(skill.lower()) + r"(?!\w)"

            if re.search(pattern, text):
                found_skills.append(skill)

    return sorted(set(found_skills))


jobs_analysis_df["extracted_skills"] = jobs_analysis_df[
    "skill_extraction_text"
].apply(
    lambda x: extract_skills(x, skill_dictionary)
)

jobs_analysis_df["skill_count"] = (
    jobs_analysis_df["extracted_skills"].apply(len)
)

print("Listings processed:", len(jobs_analysis_df))
print("Listings with at least one skill:",
      (jobs_analysis_df["skill_count"] > 0).sum())
print("Listings with no detected skills:",
      (jobs_analysis_df["skill_count"] == 0).sum())

print("\nSample extracted skills:")
print(jobs_analysis_df[
    ["title", "extracted_skills", "skill_count"]
].head(10).to_string(index=False))

Listings processed: 950
Listings with at least one skill: 392
Listings with no detected skills: 558

Sample extracted skills:
                                        title                extracted_skills  skill_count
                            Lead Data Analyst                              []            0
                                 Data Analyst                              []            0
                 Risk Technology Data Analyst                 [data analysis]            1
               Staff Data Analyst, Operations                              []            0
                   Data Analyst (AI Training)                              []            0
                      Market Data Analyst AVP                              []            0
Senior Product Data Analyst - Consumer Growth                              []            0
                                 Data Analyst                              []            0
                                Data Analysts [data analysis, data analytics]            2
                                 Data Analyst                              []            0

## 45 — Analyze Skill Demand

Calculate how frequently each technical skill appears across the current-year job listings.

In [63]:
from collections import Counter

skill_counts = Counter()

for skills in jobs_analysis_df["extracted_skills"]:
    skill_counts.update(skills)

skill_demand_df = (
    pd.DataFrame(
        skill_counts.items(),
        columns=["skill", "job_count"]
    )
    .sort_values("job_count", ascending=False)
    .reset_index(drop=True)
)

skill_demand_df["demand_percentage"] = (
    skill_demand_df["job_count"]
    / len(jobs_analysis_df)
    * 100
).round(2)

print("Unique detected skills:", len(skill_demand_df))
print("\nTop 20 skills:")
print(skill_demand_df.head(20).to_string(index=False))

Unique detected skills: 46

Top 20 skills:
                skill  job_count  demand_percentage
     machine learning        137              14.42
               python        127              13.37
        data analysis         34               3.58
                  sql         27               2.84
                  aws         26               2.74
business intelligence         26               2.74
                azure         21               2.21
                   bi         20               2.11
                    r         19               2.00
       data analytics         14               1.47
                  gcp         13               1.37
                   c#         11               1.16
                 java         10               1.05
             power bi         10               1.05
           databricks          8               0.84
                  c++          8               0.84
                excel          8               0.84
             database          6               0.63
                  nlp          6               0.63
              tableau          5               0.53

## 46 — Analyze Skill Demand by Category

Map detected skills to their broader categories to identify which technical skill groups are most prevalent in the job market.

In [64]:
skill_category_rows = []

for category, skills in skill_dictionary.items():
    for skill in skills:
        if skill in skill_counts:
            skill_category_rows.append({
                "category": category,
                "skill": skill,
                "job_count": skill_counts[skill]
            })

skill_category_df = (
    pd.DataFrame(skill_category_rows)
    .sort_values(
        ["category", "job_count"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)

print("Skill-category records:", len(skill_category_df))
print("\nSkill demand by category:")
print(
    skill_category_df
    .groupby("category")["job_count"]
    .sum()
    .sort_values(ascending=False)
)

Skill-category records: 46

Skill demand by category:
category
Programming              180
Machine Learning         149
Cloud                     72
Business Intelligence     65
Data Analysis             57
Databases & SQL           45
Tools & Platforms         24
Data Engineering          16
Name: job_count, dtype: int64

## 47 — Save Processed Skill Dataset

Save the cleaned job-level dataset and skill-demand tables for PostgreSQL, SQL analysis, and Power BI.

In [65]:
from pathlib import Path

processed_path = Path("../data/processed")
processed_path.mkdir(parents=True, exist_ok=True)

# Save job-level analytical dataset
jobs_analysis_df.to_csv(
    processed_path / "jobs_analysis.csv",
    index=False
)

# Save skill-level demand table
skill_demand_df.to_csv(
    processed_path / "skill_demand.csv",
    index=False
)

# Save skill-category table
skill_category_df.to_csv(
    processed_path / "skill_category_demand.csv",
    index=False
)

print("Processed datasets saved successfully.")
print("\nFiles:")
for file in processed_path.glob("*.csv"):
    print("-", file.name)

Processed datasets saved successfully.

Files:
- jobs_analysis.csv
- skill_category_demand.csv
- skill_demand.csv

## 48 — Prepare PostgreSQL Dataset

Prepare the processed job-market dataset for storage and analysis in PostgreSQL.

In [66]:
# Inspect the final job-level dataset before loading into PostgreSQL

print("Dataset shape:", jobs_analysis_df.shape)
print("\nColumns:")
print(jobs_analysis_df.columns.tolist())

print("\nData types:")
print(jobs_analysis_df.dtypes)

Dataset shape: (950, 21)

Columns:
['id', 'title', 'company', 'location', 'country', 'city', 'category', 'category_tag', 'contract_type', 'contract_time', 'salary_min', 'salary_max', 'salary_is_predicted', 'created', 'posting_year', 'posting_month', 'description', 'redirect_url', 'skill_extraction_text', 'extracted_skills', 'skill_count']

Data types:
id                                       str
title                                    str
company                                  str
location                                 str
country                                  str
city                                     str
category                                 str
category_tag                             str
contract_type                            str
contract_time                            str
salary_min                           float64
salary_max                           float64
salary_is_predicted                      str
created                  datetime64[us, UTC]
posting_year                           int32
posting_month                            str
description                              str
redirect_url                             str
skill_extraction_text                    str
extracted_skills                      object
skill_count                            int64
dtype: object

## 49 — PostgreSQL Database Setup

Connect the Project 10 analytical dataset to PostgreSQL for relational storage and SQL-based job-market analysis.

## 50 — Connect Python to PostgreSQL

Establish a secure connection between Python and the Project 10 PostgreSQL database.

In [67]:
import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
DB_NAME = "job_market_intelligence"
DB_USER = os.getenv("DB_USER", "postgres")
DB_PASSWORD = os.getenv("DB_PASSWORD")

conn = psycopg2.connect(
    host=DB_HOST,
    port=DB_PORT,
    database=DB_NAME,
    user=DB_USER,
    password=DB_PASSWORD
)

print("PostgreSQL connection successful.")

PostgreSQL connection successful.

## 51 — Create PostgreSQL Tables

Create relational tables for job listings and extracted skills in PostgreSQL.

In [68]:
create_tables_sql = """
CREATE TABLE IF NOT EXISTS jobs (
    id BIGINT PRIMARY KEY,
    title TEXT,
    company TEXT,
    location TEXT,
    country TEXT,
    city TEXT,
    category TEXT,
    category_tag TEXT,
    contract_type TEXT,
    contract_time TEXT,
    salary_min NUMERIC,
    salary_max NUMERIC,
    salary_is_predicted BOOLEAN,
    created TIMESTAMPTZ,
    posting_year INTEGER,
    posting_month TEXT,
    description TEXT,
    redirect_url TEXT,
    skill_extraction_text TEXT,
    skill_count INTEGER
);

CREATE TABLE IF NOT EXISTS job_skills (
    job_id BIGINT,
    skill TEXT,
    PRIMARY KEY (job_id, skill),
    FOREIGN KEY (job_id) REFERENCES jobs(id)
);
"""

with conn.cursor() as cur:
    cur.execute(create_tables_sql)

conn.commit()

print("PostgreSQL tables created successfully.")

PostgreSQL tables created successfully.

## 52 — Load Jobs into PostgreSQL

Load the cleaned job-market dataset into the PostgreSQL `jobs` table.

In [69]:
from psycopg2.extras import execute_values

job_columns = [
    "id",
    "title",
    "company",
    "location",
    "country",
    "city",
    "category",
    "category_tag",
    "contract_type",
    "contract_time",
    "salary_min",
    "salary_max",
    "salary_is_predicted",
    "created",
    "posting_year",
    "posting_month",
    "description",
    "redirect_url",
    "skill_extraction_text",
    "skill_count"
]

jobs_load_df = jobs_analysis_df[job_columns].copy()

# Convert pandas missing values to Python None
jobs_load_df = jobs_load_df.where(
    jobs_load_df.notna(),
    None
)

records = list(
    jobs_load_df.itertuples(index=False, name=None)
)

insert_jobs_sql = f"""
INSERT INTO jobs ({", ".join(job_columns)})
VALUES %s
ON CONFLICT (id) DO NOTHING;
"""

with conn.cursor() as cur:
    execute_values(
        cur,
        insert_jobs_sql,
        records
    )

conn.commit()

print("Jobs loaded:", len(records))

Jobs loaded: 950

In [70]:
print("Python analytical rows:", len(jobs_analysis_df))
print("Python load rows:", len(records))

with conn.cursor() as cur:
    cur.execute("SELECT COUNT(*) FROM jobs;")
    db_job_count = cur.fetchone()[0]

print("PostgreSQL jobs:", db_job_count)

Python analytical rows: 950
Python load rows: 950
PostgreSQL jobs: 991

In [71]:
id="m7k2px"
# Clear the failed PostgreSQL transaction
conn.rollback()

# Reset both Project 10 tables
with conn.cursor() as cur:
    cur.execute("DROP TABLE IF EXISTS job_skills;")
    cur.execute("DROP TABLE IF EXISTS jobs;")
    cur.execute(create_tables_sql)

conn.commit()

# Prepare exactly the 938 analytical rows
jobs_load_df = jobs_analysis_df[job_columns].copy()

jobs_load_df = jobs_load_df.where(
    jobs_load_df.notna(),
    None
)

records = list(
    jobs_load_df.itertuples(index=False, name=None)
)

insert_jobs_sql = f"""
INSERT INTO jobs ({", ".join(job_columns)})
VALUES %s;
"""

with conn.cursor() as cur:
    execute_values(
        cur,
        insert_jobs_sql,
        records
    )

conn.commit()

# Verify
with conn.cursor() as cur:
    cur.execute("SELECT COUNT(*) FROM jobs;")
    db_job_count = cur.fetchone()[0]

print("Python analytical rows:", len(jobs_analysis_df))
print("Rows inserted:", len(records))
print("PostgreSQL jobs:", db_job_count)

Python analytical rows: 950
Rows inserted: 950
PostgreSQL jobs: 950

In [72]:
print("jobs_df rows:", len(jobs_df))
print("jobs_analysis_df rows:", len(jobs_analysis_df))

print("\nDuplicate job IDs in jobs_analysis_df:",
      jobs_analysis_df["id"].duplicated().sum())

print("\nUnique job IDs:",
      jobs_analysis_df["id"].nunique())

print("\nPosting years:")
print(jobs_analysis_df["posting_year"].value_counts().sort_index())

jobs_df rows: 950
jobs_analysis_df rows: 950

Duplicate job IDs in jobs_analysis_df: 0

Unique job IDs: 950

Posting years:
posting_year
2026    950
Name: count, dtype: int64

## 53 — Load Extracted Skills into PostgreSQL

Load the extracted job-level skills into the PostgreSQL `job_skills` table for relational and SQL-based analysis.

In [73]:
skill_records = []

for _, row in jobs_analysis_df.iterrows():
    for skill in row["extracted_skills"]:
        skill_records.append(
            (int(row["id"]), skill)
        )

insert_skills_sql = """
INSERT INTO job_skills (job_id, skill)
VALUES %s
ON CONFLICT (job_id, skill) DO NOTHING;
"""

with conn.cursor() as cur:
    execute_values(
        cur,
        insert_skills_sql,
        skill_records
    )

conn.commit()

with conn.cursor() as cur:
    cur.execute("SELECT COUNT(*) FROM job_skills;")
    skill_row_count = cur.fetchone()[0]

print("Skill records prepared:", len(skill_records))
print("PostgreSQL skill records:", skill_row_count)

Skill records prepared: 608
PostgreSQL skill records: 608

## 54 — Top In-Demand Skills

Identify the most frequently detected skills across current job listings.

In [74]:
top_skills_sql = """
SELECT
    skill,
    COUNT(*) AS job_count
FROM job_skills
GROUP BY skill
ORDER BY job_count DESC, skill
LIMIT 15;
"""

with conn.cursor() as cur:
    cur.execute(top_skills_sql)
    top_skills = cur.fetchall()

top_skills

[('machine learning', 137),
 ('python', 127),
 ('data analysis', 34),
 ('sql', 27),
 ('aws', 26),
 ('business intelligence', 26),
 ('azure', 21),
 ('bi', 20),
 ('r', 19),
 ('data analytics', 14),
 ('gcp', 13),
 ('c#', 11),
 ('java', 10),
 ('power bi', 10),
 ('c++', 8)]

## 55 — Skills by Job Category

Compare skill demand across job categories.

In [75]:
category_skills_sql = """
SELECT
    j.category,
    js.skill,
    COUNT(*) AS job_count
FROM jobs j
JOIN job_skills js
    ON j.id = js.job_id
GROUP BY j.category, js.skill
ORDER BY j.category, job_count DESC;
"""

with conn.cursor() as cur:
    cur.execute(category_skills_sql)
    category_skills = cur.fetchall()

category_skills[:20]

[('Accounting & Finance Jobs', 'python', 2),
 ('Accounting & Finance Jobs', 'c++', 1),
 ('Creative & Design Jobs', 'business intelligence', 1),
 ('Engineering Jobs', 'machine learning', 8),
 ('IT Jobs', 'machine learning', 129),
 ('IT Jobs', 'python', 125),
 ('IT Jobs', 'data analysis', 34),
 ('IT Jobs', 'sql', 27),
 ('IT Jobs', 'aws', 26),
 ('IT Jobs', 'azure', 21),
 ('IT Jobs', 'bi', 20),
 ('IT Jobs', 'business intelligence', 20),
 ('IT Jobs', 'r', 16),
 ('IT Jobs', 'gcp', 13),
 ('IT Jobs', 'data analytics', 12),
 ('IT Jobs', 'c#', 11),
 ('IT Jobs', 'java', 10),
 ('IT Jobs', 'power bi', 10),
 ('IT Jobs', 'databricks', 8),
 ('IT Jobs', 'c++', 7)]

## 56 — Location & Role Analysis

Analyze job demand by location and job title using PostgreSQL.

In [76]:
location_role_sql = """
SELECT
    city,
    COUNT(*) AS job_count
FROM jobs
GROUP BY city
ORDER BY job_count DESC
LIMIT 15;
"""

with conn.cursor() as cur:
    cur.execute(location_role_sql)
    location_demand = cur.fetchall()

print("Top job locations:")
for row in location_demand:
    print(row)

Top job locations:
('London', 330)
('Manchester', 216)
('Birmingham', 106)
('Farringdon', 35)
('Balsall Heath', 30)
('The City', 27)
('Manchester Science Park', 26)
('Rusholme', 22)
('South West London', 13)
('Charing Cross', 9)
('South East London', 9)
('Covent Garden', 7)
('Holborn', 6)
('Hulme', 6)
('Bournbrook', 6)

## 57 — Salary Analysis

Analyze available salary ranges across current job listings.

In [77]:
salary_sql = """
SELECT
    COUNT(*) AS jobs_with_salary,
    ROUND(AVG(salary_min), 2) AS avg_salary_min,
    ROUND(AVG(salary_max), 2) AS avg_salary_max,
    MIN(salary_min) AS min_salary,
    MAX(salary_max) AS max_salary
FROM jobs
WHERE salary_min > 0
  AND salary_max > 0;
"""

with conn.cursor() as cur:
    cur.execute(salary_sql)
    salary_summary = cur.fetchone()

print("Salary summary:")
print(salary_summary)

Salary summary:
(943, Decimal('62621.89'), Decimal('67439.26'), Decimal('1.0'), Decimal('250000.0'))

In [78]:
jobs_df = jobs_df[
    jobs_df["posting_year"] == 2026
].copy()

jobs_df = jobs_df.reset_index(drop=True)

print("Current analytical listings:", len(jobs_df))
print("Earliest analytical posting:", jobs_df["created"].min())
print("Latest analytical posting:", jobs_df["created"].max())

Current analytical listings: 950
Earliest analytical posting: 2026-01-06 15:09:28+00:00
Latest analytical posting: 2026-09-13 12:46:53+00:00

In [79]:
jobs_df.shape

(950, 26)